server:
  port: 12345

management:
  endpoint:
    gateway:
      enabled: false

spring:
  application:
    name: gateway
  redis:
    port: 6379
    database: 0
    host: 10.24.20.55
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
    timeout: 5000ms
  cloud:
    nacos:
      discovery:
        server-addr: 10.24.20.55:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
